### ISSUE TITLE
Numeric comparison of @l with LoggingFilterSwitch

### ISSUE THREAD

**Issue by reitffunk** [serilog/serilog-expressions#104]
hello guys,

we are controlling out log filtering with the `LoggingFilterSwitch `(NOT the `LoggingLevelSwitch`).

Following expression gives us all the log statements for `Fatal`, `Error `and `Information`.

```
@l = 'Fatal' or
@l = 'Error' or
@l = 'Warning'
@l = 'Information'
```

It would be great if we could just say

`@l >= 'Information'`

with the expectation that this logs every level same and above `Information`.

You might think that its not so important to save these lines. But our expression can get bigger as we use it also for specific log properties we pushed to the `LogContext`.

For example:

```
@l = 'Fatal' or
@l = 'Error' or
@l = 'Warning' or
(@p['system'] = 'system1' and (@l = 'Fatal' or @l = 'Error' or @l = 'Warning' or @l = 'Information' or @l = 'Debug')
```

would be simplified to

```
@l >= 'Warning' or
(@p['system'] = 'system1' and @l >= 'Debug')
```

It is also not really possible with that approach to use the overall `MinimumLogLevel`. If you would set the `MinimumLogLevel` overall to 'Information' no 'Debug' comes through from the expression anymore. That's no issue for me, just want to emphasize that we are not able to control it with that either.

Something more: The `LoggingFilterSwitch` gets no love in the documentation at all. Is it possible to contribute to the docs here? It's basically a really really nice feature that helps us to dynamically set the logging from outside in a IoT system with thousands of devices.

**Comment by nblumhardt** [comment]
Hi! `@l not in ['Verbose', 'Debug']` might be a more succinct version of what you need.

Unfortunately things get messy once the implementation needs to double dispatch operators based on both the left and right operands. It could be done, but doesn't seem worth it at this point.

Some docs for `LoggingFilterSwitch` would be awesome, if you have the chance to send a PR! 👍

**Comment by reitffunk** [comment]
Your suggestion would be even nicer, indeed!

Thanks for the answer, fair enough if it has no priority. I will see, what I can do about the docs.
