### ISSUE TITLE
replace all delimiters in SourceContext - replace separator with space - for example

### ISSUE THREAD

**Issue by Simonl9l** [serilog/serilog-expressions#120]
**Is your feature request related to a problem? Please describe.**
Whilst `SourceContext`'s are other namespace'd types they canals be what ever one defines. For differing format outputs say console vs log file, one might want to make the console more readable.

It would be good to be able to replace all occurrences of say `.` in the `SourceContext` with ` ` (space).   

**Describe the solution you'd like**
not sure?

**Describe alternatives you've considered**
it seem one could use `for each` to Join things back together, but nothing seem available to do the split.

**Comment by nblumhardt** [comment]
Hi! Right now I think plugging in a user-defined function will be the way to go:

https://github.com/serilog/serilog-expressions?tab=readme-ov-file#implementing-user-defined-functions

Hope this helps,
Nick
