### ISSUE TITLE
Unable to escape `{` and `}` characters in templates?

### ISSUE THREAD

**Issue by julealgon** [serilog/serilog-expressions#15]
I'm trying to create a nested Json in my log template, however I cannot escape the `{` and `}` characters. Here is what I want to do:

```csharp
.WriteTo.Console(new ExpressionTemplate(
    "{ {timestamp: @t, bla: { inner: @p['SomeProperty´] }, level: @l, message: @m, exception: @x, ..@p} }\n",
```

This is what I've tried thus far:
- Duplicating the curly braces
- Duplicating and adding spaces between them (similar to the starting and ending characters)
- Adding `'` characters around the braces

After trying all that and reading the documentation a bit more, it appears that "nested properties" might not be supported out of the box?

This seems weird to me considering the template generates text at the end of the day. It should be possible to escape the `{` characters somehow.

I think I could make this work by creating a new user-defined function that works on properties and returns a `StructuralValue` but I thought it would be possible to just make it inline.

Am I missing something? Would it be necessary to add new features to the DSL to support this scenario?

**Comment by julealgon** [comment]
Silly mistake on my end. After trying this a bit more, I realized `'SomeProperty´` had a `´`  character at the end instead of a `'` character :(

It works property if I pass in the property name correctly without the need for escaping anything.

**Comment by julealgon** [comment]
Leaving this open in case you want to add an example with nested Json to the readme or the samples. It would've helped me a bit here so perhaps there is some value in it.

Otherwise, feel free to close this.

**Comment by nblumhardt** [comment]
Thanks for the note. I think in general we probably need a new article covering all of the syntax, will close for now though.
