### ISSUE TITLE
Expose "unmentioned properties" somehow

### ISSUE THREAD

**Issue by julealgon** [serilog/serilog-expressions#17]
It would be interesting if there was a way to access "every property that was not explicitly mentioned" in a template.

For example, say I need to relocate a few properties to match a given log aggregator. I can "move" them in the template to whatever position I want, which is actually much nicer than having to code this in an enricher. 

Exemple:

- `{ {needThisToBeNested: { nestedValue: @p['someProperty'] }, ..@p} }`

Notice how I basically "move" the `someProperty` value into a nested structure. However, the `..@p` at the end will end up emitting the same property again in the root level.

I'd like for a way to expand "only the properties that have not been used explicitly in the template", so that the expansion at the end did not include a duplicate of `someProperty`.

I assume this is currently impossible without writing a custom user-defined function that filters `@p`, which would then force me to pass a list of all properties to filter manually and create substantial verbosity and repetition on my template. Something like:

- `{ {needThisToBeNested: { nestedValue: @p['someProperty'] }, ..FilterThis(@p, 'someProperty')} }`

I imagine `FilterThis` would also not be the most efficient thing in the world, since it needs to match a `StructuralValue`, inspect all inner properties and then return a new `StructuralValue` without the ones that match the list of parameters.

Having said that, after trying a quick sample, user-defined functions do not appear to allow extra parameters in them:

```csharp
public static LogEventPropertyValue? FilterThis(LogEventPropertyValue? property, params string[] filters)
```
> **System.ArgumentException:** The function `FilterThis` requires 1 arguments.

So now I actually don't know how to filter the properties to avoid the duplication.

**Comment by julealgon** [comment]
I just thought about a way to cleanly support this.

**Suggestion:** Provide a `ExtractElementAt` function, that is similar to `ElementAt`, but instead of just returning the property, actually removes it from it's parent object.

I imagine this could be coded around this overload: [Dictionary.Remove(TKey, TValue)](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.remove?view=net-5.0#System_Collections_Generic_Dictionary_2_Remove__0__1__)

This would very cleanly support what I need and should be (relatively) easy to implement:

- `{ {needThisToBeNested: { nestedValue: ExtractElementAt(@p, 'someProperty') }, ..@p} }`

**Comment by nblumhardt** [comment]
Hi Juliano! What you need is:

```
{ {needThisToBeNested: { nestedValue: someProperty }, ..@p, someProperty: undefined()} }
```

If an entry in an object literal is undefined (like the last mention of `someProperty`) it's deleted from the resulting object.

There's a test (https://github.com/serilog/serilog-expressions/blob/dev/test/Serilog.Expressions.Tests/Cases/expression-evaluation-cases.asv#L21) but not any documentation yet IIRC :-)

**Comment by julealgon** [comment]
Hey Nick, I'm sorry but I don't quite follow your suggestion there, the syntax looks unexpected to me.

Are you saying that this:
- `{ {propertyLabel: @p['propertyName']} }`

is the same as 
- `{ {propertyLabel: propertyName} }`

?

**Comment by nblumhardt** [comment]
Thanks for the follow-up. Yes, `propertyName` and `@p['propertyName']` are two different ways of saying the same thing - the top level properties of the event can be used directly (`propertyName`), but that is just shorthand for accessing the values in `@p`, and if the property name isn't a valid identifier (e.g. `property-name`) then accessing it through `@p` is the only way to go.

Made some small changes in the README to clarify this, but might add some more info there when I have a chance.

**Comment by julealgon** [comment]
Ohhh ok. I was under the impression the shorthand syntax was only used for the main properties (level, message, template, etc).

Now I understand your sample, and it is a good workaround indeed. Still not ideal though, considering I'll probably have to "move" a dozen or so properties this way, which will force me to add a lot of cruft to the end of the template duplicating every property name.

For that reason, I still think an "extract"-like method would be useful.

**Comment by nblumhardt** [comment]
👍 currently the purely-functional nature of the language makes an "extract" difficult to visualize; it's likely this is as good as it will get, for now.

Serilog output templates treat `@Properties` as "unmentioned properties", but the overall design/mechanism doesn't carry across - I think emulating it would result in some nasty implementation hacks :-)
