### ISSUE TITLE
File Logging with ExpressionTemplate

### ISSUE THREAD

**Issue by Ryanm0821** [serilog/serilog-expressions#33]
This is more of a question than an issue, but is it possible to use ExpressionTemplate with writing the logs to a file? All examples on the readme are only for ".WriteTo.Console", and when looking at the WriteTo.File documentation, there is no ITextFormatter argument. I've also tried finding other examples outside of GitHub, but I'm not having any luck..

Any help will be appreciated.

Thanks.

**Comment by nblumhardt** [comment]
Hi! `WriteTo.File()` has an overload that accepts `ITextFormatter` as the first arg:

```csharp
    .WriteTo.File(new ExpressionTemplate(...), "log.txt", ...)
```

HTH!

**Comment by Ryanm0821** [comment]
@nblumhardt oh lol wow. Can't believe I missed that. Thanks so much!
