### ISSUE TITLE
Multiple exclusion for RequestPath

### ISSUE THREAD

**Issue by biplovkc** [serilog/serilog-expressions#37]
Health request exclusion works fine, but when I call my api it loads redoc and other js or json files 
This works fine 
`Filter.ByExcluding("RequestPath like '/health%'")`
but following does not
`Filter.ByExcluding("RequestPath like '/health%' or '/redoc%'")`
following does not even compile
`Filter.ByExcluding("RequestPath like '/health%' or like '/redoc%'")`
Second or(i.e. redoc) is still logged. Anything I am doing wrong?

**Comment by nblumhardt** [comment]
Hi! You'll need:

```csharp
Filter.ByExcluding("RequestPath like '/health%' or RequestPath like '/redoc%'")
```

HTH!

**Comment by biplovkc** [comment]
> Hi! You'll need:
> 
> ```cs
> Filter.ByExcluding("RequestPath like '/health%' or RequestPath like '/redoc%'")
> ```
> 
> HTH!

yes this worked thank you

**Comment by nblumhardt** [comment]
Great, thanks for the follow-up 👍
