### ISSUE TITLE
Introduction of Nullable nuget package is breaking

### ISSUE THREAD

**Issue by Skoucail** [serilog/serilog-expressions#53]
Starting with release 3.2.0 of serilog-expressions the package has a reference to the Nullable nuget package for lower frameworks. (#47 )
We already have 2 cases where this is not working and we cant upgrade to version 3.2.0.

1st case:
We have a C# project in .net framework 4.6.1
After upgrading to version 3.2.0 and automatically installing the Nullable package our build gives errors.
![image](https://user-images.githubusercontent.com/20516786/137474717-20af637d-60ca-411a-857d-341226acdb7b.png)

2nd case:
We have a VB.NET project in .net framework 4.6.1.
Here the Nullable packages adds the source code files in C# files.
So those filles will never get build. So any code from serilog-expressions that expect the nullable attributes to be available will error.

Including the 1 attribute used into serilog-expressions worked in all cases and removing it only seem to have a downside for backwards compatibility. Maybe this change should be reverted?

**Comment by nblumhardt** [comment]
Thanks, yes, it seems like it may be better to back this out 👍 

This will also cause some pain for _Serilog_, we should reconsider that change over there.

CC @SimonCropp - any thoughts?

**Comment by SimonCropp** [comment]
i think this has already been fixed. @Skoucail can you try version 3.2.1-dev-00071

**Comment by nblumhardt** [comment]
Thanks for looking in @SimonCropp ; I checked the Nullable source, it still uses `#nullable enable` throughout, and the README carries a warning that it can only be consumed using C# 8.

https://github.com/manuelroemer/Nullable#quickstart

**Comment by nblumhardt** [comment]
Ah sorry :-D my bad; yes, @SimonCropp  is correct, we now mark these as private assets.

(Just finished my second coffee 😅 )

**Comment by SimonCropp** [comment]
it works for my other 150 nugets 😜

**Comment by nblumhardt** [comment]
:-D

Raised #53, will merge once it's green!

**Comment by Skoucail** [comment]
I just pulled version 3.2.1 (seems its already released) in one of the projects I had issues in.
No dependency for the Nullable nuget package was added to my project => no build errors.

Thx for the fix!
