### ISSUE TITLE
Cannot create instance of type 'Serilog.Formatting.ITextFormatter' because it is either abstract or an interface

### ISSUE THREAD

**Issue by FJGR65** [serilog/serilog-expressions#57]
At runtime i have this error:

```csharp
System.InvalidOperationException
  HResult=0x80131509
  Mensaje = Cannot create instance of type 'Serilog.Formatting.ITextFormatter' because it is either abstract or an interface.
  Origen = Microsoft.Extensions.Configuration.Binder
  Seguimiento de la pila:
   en Microsoft.Extensions.Configuration.ConfigurationBinder.CreateInstance(Type type)
   en Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config, BinderOptions options)
   en Microsoft.Extensions.Configuration.ConfigurationBinder.Get(IConfiguration configuration, Type type, Action`1 configureOptions)
   en Microsoft.Extensions.Configuration.ConfigurationBinder.Get(IConfiguration configuration, Type type)
   en Serilog.Settings.Configuration.ObjectArgumentValue.ConvertTo(Type toType, ResolutionContext resolutionContext)
   en Serilog.Settings.Configuration.ConfigurationReader.<>c__DisplayClass21_2.<CallConfigurationMethods>b__3(<>f__AnonymousType9`2 <>h__TransparentIdentifier0)
   en System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   en System.Linq.Enumerable.SelectListPartitionIterator`2.ToList()
   en Serilog.Settings.Configuration.ConfigurationReader.CallConfigurationMethods(ILookup`2 methods, IList`1 configurationMethods, Object receiver)
   en Serilog.Settings.Configuration.ConfigurationReader.ApplySinks(LoggerConfiguration loggerConfiguration)
   en Serilog.Settings.Configuration.ConfigurationReader.Configure(LoggerConfiguration loggerConfiguration)
   en Serilog.Configuration.LoggerSettingsConfiguration.Settings(ILoggerSettings settings)
   en Serilog.ConfigurationLoggerConfigurationExtensions.Configuration(LoggerSettingsConfiguration settingConfiguration, IConfiguration configuration, String sectionName, DependencyContext dependencyContext)
```

appsettings.json

```json
  "Serilog": {
    "Using": [ "Serilog.Sinks.Console", "Serilog.Sinks.File", "Serilog.Enrichers.ClientInfo", "Serilog.Expressions" ],
    "MinimumLevel": {
      "Default": "Verbose",
      "Override": {
        "Microsoft": "Verbose",
        "Microsoft.AspNetCore": "Verbose",
        "Microsoft.Hosting.Lifetime": "Verbose",
        "System": "Verbose"
      }
    },
    "WriteTo": [
      {
        "Name": "File",
        "Args": {
          "path": "%StoredFilesPath%\\serilog-Desarrollo-.json",
          "formatter": {
            "type": "Serilog.Templates.ExpressionTemplate, Serilog.Expressions",
            "template": "{ {T:ToString(@t, 'HH:mm:ss.fffffff'), L:coalesce({Information: 'INF', Warning: 'WRN', Error: 'ERR', Fatal: 'FTL', Verbose: 'VRB', Debug: 'DBG'}[@l], @l), SRC:if SourceContext <> 'Serilog.AspNetCore.RequestLoggingMiddleware' then SourceContext else undefined(), @m, EsBoot2:EsBoot(ClientAgent), EsBoot1:if Contains(ClientAgent, 'bot') then 'Si' else 'No', Pag:Concat(RequestScheme, '://', RequestHost, Resource), Ip:ClientIp, Idf:CorrelationId, EvId:EventId, IdMsgT:ToString(@i, 'X8'), @mt, ..@p, RequestScheme: undefined(), RequestHost: undefined(), Resource: undefined(), ClientIp: undefined(), CorrelationId: undefined(), EventId: undefined(), \r\n@x} }\r\n",
            "nameResolver": "PuedeSerBoot"
          },
          "rollingInterval": "Hour",
          "rollOnFileSizeLimit": true,
          "retainedFileCountLimit": null,
          "buffered": false,
          "flushToDiskInterval": 1,
          "shared": true
        }
      },
      {
        "Name": "Console"
      }
    ],
    "Enrich": [ "FromLogContext", "WithClientIp", "WithClientAgent" ],
    "Destructure": [
      {
        "Name": "ToMaximumDepth",
        "Args": { "maximumDestructuringDepth": 6 }
      },
      {
        "Name": "ToMaximumStringLength",
        "Args": { "maximumStringLength": 1000 }
      },
      {
        "Name": "ToMaximumCollectionCount",
        "Args": { "maximumCollectionCount": 20 }
      }
    ]
  },
```

```csharp
   StaticMemberNameResolver myFunctions = new(typeof(PuedeSerBoot));
    CompiledExpression expr = SerilogExpression.Compile("EsBoot(ClientAgent)", null, myFunctions);

    Log.Logger = new LoggerConfiguration()
      .ReadFrom.Configuration(config, "Serilog")
      .CreateLogger(); //.CreateBootstrapLogger();`
```

Versions:
```xml
 <ItemGroup>
    <PackageReference Include="AspNetCoreRateLimit" Version="4.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="6.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.2.2" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="6.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="6.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyModel" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="6.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="6.0.0" />
    <PackageReference Include="Serilog" Version="2.10.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="4.1.0" />
    <PackageReference Include="Serilog.Enrichers.ClientInfo" Version="1.1.4" />
    <PackageReference Include="Serilog.Expressions" Version="3.2.1" />
    <PackageReference Include="Serilog.Formatting.Compact" Version="1.1.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="3.3.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="4.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
  </ItemGroup>
```

**Comment by FJGR65** [comment]
Well, I have found an alternative by creating an "enrich".

Since I am using "Serilog.Enrichers.ClientInfo" I have simply created the following class:

`

using Serilog.Core;
using Serilog.Events;

namespace Serilog.Enrichers
{
  public class ClientAgentBoootEnricher : ILogEventEnricher
  {
    private const string ClientAgentPropertyName = "ClientBootAgent";
    private const string ClientAgentItemKey = "Serilog_ClientBootAgent";

    private readonly IHttpContextAccessor _contextAccessor;

    public ClientAgentBoootEnricher() : this(new HttpContextAccessor()) { }
    internal ClientAgentBoootEnricher(IHttpContextAccessor contextAccessor)
    {
      _contextAccessor = contextAccessor;
    }

    public void Enrich(LogEvent logEvent, ILogEventPropertyFactory propertyFactory)
    {
      var httpContext = _contextAccessor.HttpContext;
      if (httpContext == null)
        return;

      if (httpContext.Items[ClientAgentItemKey] is LogEventProperty logEventProperty)
      {
        logEvent.AddPropertyIfAbsent(logEventProperty);
        return;
      }

      var agentName = httpContext.Request.Headers["User-Agent"];
      var val= new ScalarValue(agentName.Contains("bot") ? "Si" : "No"); //Obviously, the desired complexity can be added here. 

      var clientAgentProperty = new LogEventProperty(ClientAgentPropertyName, val);
      httpContext.Items.Add(ClientAgentItemKey, clientAgentProperty);

      logEvent.AddPropertyIfAbsent(clientAgentProperty);
    }
  }
}


`

The code that initializes Serilog is as follows:

`
   Log.Logger = new LoggerConfiguration()
      .Enrich.With<ClientAgentBoootEnricher>()
      .ReadFrom.Configuration(config, "Serilog")
      .CreateLogger();
`

And lastly, the appsettings.json looks like this: 

  "Serilog": {
    "Using": [ "Serilog.Sinks.Console", "Serilog.Sinks.File", "Serilog.Enrichers.ClientInfo", "Serilog.Expressions" ],
    "MinimumLevl": {
      "Default": "Verbose",
      "Override": {
        "Microsoft": "Verbose",
        "Microsoft.AspNetCore": "Verbose",
        "Microsoft.Hosting.Lifetime": "Verbose",
        "System": "Verbose"
      }
    },
    "WriteTo": [
      {
        "Name": "File",
        "Args": {
          "path": "%StoredFilesPath%\\serilog-Desarrollo-.json",
          "formatter": {
            "type": "Serilog.Templates.ExpressionTemplate, Serilog.Expressions",
            "template": "{ {T:ToString(@t, 'HH:mm:ss.fffffff'), L:coalesce({Information: 'INF', Warning: 'WRN', Error: 'ERR', Fatal: 'FTL', Verbose: 'VRB', Debug: 'DBG'}[@l], @l), SRC:if SourceContext <> 'Serilog.AspNetCore.RequestLoggingMiddleware' then SourceContext else undefined(), @m, **EsBoot3:ClientBootAgent**, EsBoot1:if Contains(ClientAgent, 'bot') then 'Si' else 'No', Pag:Concat(RequestScheme, '://', RequestHost, Resource), Ip:ClientIp, Idf:CorrelationId, EvId:EventId, IdMsgT:ToString(@i, 'X8'), @mt, ..@p, RequestScheme: undefined(), RequestHost: undefined(), Resource: undefined(), ClientIp: undefined(), CorrelationId: undefined(), EventId: undefined(), RequestMethod: undefined(), RequestPath: undefined(), StatusCode: undefined(), Elapsed: undefined(), SourceContext: undefined(), RequestId: undefined(), ConnectionId: undefined(), \r\n@x} }\r\n"
          },
          "rollingInterval": "Hour",
          "rollOnFileSizeLimit": true,
          "retainedFileCountLimit": null,
          "buffered": false,
          "flushToDiskInterval": 1,
          "shared": true
        }
      },
      {
        "Name": "Console"
      }
    ],
    "Enrich": [ "FromLogContext", "WithClientIp", "WithClientAgent" ],
    "Destructure": [
      {
        "Name": "ToMaximumDepth",
        "Args": { "maximumDestructuringDepth": 6 }
      },
      {
        "Name": "ToMaximumStringLength",
        "Args": { "maximumStringLength": 1000 }
      },
      {
        "Name": "ToMaximumCollectionCount",
        "Args": { "maximumCollectionCount": 20 }
      }
    ]
  },




I just have to thank the work of all the contributors to this package that allows the rest of us to simplify our lives. Thanks.

**Comment by skomis-mm** [comment]
Hi @FJGR65 ,
for the original question I think you need specify full type name for `PuedeSerBoot`:
```json
"nameResolver": "[NameSpace].PuedeSerBoot, [Assembly]"
```
(also, don't forget to include it to the `Using` section)

**Comment by FJGR65** [comment]
> 

Thank you very much Sergey, but it still doesn't work.

The suggested changes are as follows:

    "Using": [ "Serilog.Sinks.Console", "Serilog.Sinks.File", "Serilog.Enrichers.ClientInfo", "Serilog.Expressions", "**MyProgram**" ],
...

          "formatter": {
            "type": "Serilog.Templates.ExpressionTemplate, Serilog.Expressions",
            "template": "{ {T:ToString(@t, 'HH:mm:ss.fffffff'), L:coalesce({Information: 'INF', Warning: 'WRN', Error: 'ERR', Fatal: 'FTL', Verbose: 'VRB', Debug: 'DBG'}[@l], @l), SRC:if SourceContext <> 'Serilog.AspNetCore.RequestLoggingMiddleware' then SourceContext else undefined(), @m, **EsBoot2:EsBoot(ClientAgent)**, EsBoot1:if Contains(ClientAgent, 'bot') then 'Si' else 'No', Pag:Concat(RequestScheme, '://', RequestHost, Resource), Ip:ClientIp, Idf:CorrelationId, EvId:EventId, IdMsgT:ToString(@i, 'X8'), @mt, ..@p, RequestScheme: undefined(), RequestHost: undefined(), Resource: undefined(), ClientIp: undefined(), CorrelationId: undefined(), EventId: undefined(), RequestMethod: undefined(), RequestPath: undefined(), StatusCode: undefined(), Elapsed: undefined(), SourceContext: undefined(), RequestId: undefined(), ConnectionId: undefined(), \r\n@x} }\r\n",
            "nameResolver": "**MyProgram.UtilidadesWeb.Extensiones.PuedeSerBoot, MyProgram**"
          },


In the first post I forgot to show the function. I show it now: 

`
using Serilog.Events;

namespace MyProgram.UtilidadesWeb.Extensiones
{
  public static class PuedeSerBoot
  {
    public static LogEventPropertyValue? EsBoot(StringComparison comparison, LogEventPropertyValue? clienteAgente)
    {
      if (clienteAgente is ScalarValue sv && sv.Value is string s)
        return new ScalarValue(s.Contains("bot", comparison) ? "Si" : "No");

      // Undefined - argument was not a string.
      return null;
    }
  }
}

`

**Comment by skomis-mm** [comment]
@FJGR65 try to change to concrete type (not the `static class`)

**Comment by FJGR65** [comment]
Sorry, Sergey, it still doesn't work.

I have tried to remove "static class" for "class" and it doesn't work.

I have also tried changing the "public static LogEventPropertyValue? ..." method to "static LogEventPropertyValue? ..." and it doesn't work either. In this case, obviously, the error is in: "CompiledExpression expr = SerilogExpression.Compile (" EsBoot (ClientAgent) ", null, myFunctions);", but if I comment it, it still doesn't work.

**Comment by skomis-mm** [comment]
> Sorry, Sergey, it still doesn't work.
> 
> I have tried to remove "static class" for "class" and it doesn't work.
> 
> I have also tried changing the "public static LogEventPropertyValue? ..." method to "static LogEventPropertyValue? ..." and it doesn't work either. In this case, obviously, the error is in: "CompiledExpression expr = SerilogExpression.Compile (" EsBoot (ClientAgent) ", null, myFunctions);", but if I comment it, it still doesn't work.

just forgot you should also implement `NameResolver` for the  "nameResolver" parameter:
```csharp
public class PuedeSerBoot : NameResolver
{
      // .. 
}
```

**Comment by FJGR65** [comment]
Thank you very much, Sergey. You've been very kind.

Now it works. I put the code so that other people can learn from your knowledge. Thanks.

The user-defined function is:


`
using Serilog.Events;
using Serilog.Expressions;
using System.Diagnostics.CodeAnalysis;
using System.Reflection;

namespace MyProgram.UtilidadesWeb.Extensiones
{
  public class PuedeSerBoot : NameResolver
  {
    /// <summary>
    /// Match a function name to a method that implements it.
    /// </summary>
    /// <param name="name">The function name as it appears in the expression source. Names are not case-sensitive.</param>
    /// <param name="implementation">A <see cref="MethodInfo"/> implementing the function.</param>
    /// <returns><c>True</c> if the name could be resolved; otherwise, <c>false</c>.</returns>
    /// <remarks>The method implementing a function should be <c>static</c>, return <see cref="LogEventPropertyValue"/>,
    /// and accept parameters of type <see cref="LogEventPropertyValue"/>. If the <c>ci</c> modifier is supported,
    /// a <see cref="StringComparison"/> should be included in the argument list. If the function is culture-specific,
    /// an <see cref="IFormatProvider"/> should be included in the argument list.</remarks>
    public override bool TryResolveFunctionName(string name, [MaybeNullWhen(false)] out MethodInfo implementation)
    {
      Type t = Type.GetType("MyProgram.UtilidadesWeb.Extensiones.PuedeSerBoot");
      implementation = t.GetMethod(name);
      return true;
    }

    /// <summary>
    /// Provide a value for a non-<see cref="LogEventPropertyValue"/> parameter. This allows user-defined state to
    /// be threaded through user-defined functions.
    /// </summary>
    /// <param name="parameter">A parameter of a method implementing a user-defined function, which could not be
    /// bound to any of the standard runtime-provided values or operands.</param>
    /// <param name="boundValue">The value that should be provided when the method is called.</param>
    /// <returns><c>True</c> if the parameter could be bound; otherwise, <c>false</c>.</returns>
    public override bool TryBindFunctionParameter(ParameterInfo parameter, [MaybeNullWhen(false)] out object boundValue)
    {
      //This method not is called.
      boundValue = null;
      return false;
    }

    public static LogEventPropertyValue? EsBoot(StringComparison comparison, LogEventPropertyValue? clienteAgente)
    {
      if (clienteAgente is ScalarValue sv && sv.Value is Microsoft.Extensions.Primitives.StringValues s)
        return new ScalarValue(s.ToString().Contains("bot", comparison) ? "Si" : "No");

      // Undefined - argument was not a string.
      return null;
    }
  }
}
`

The class is quite different from what is indicated in: [https://github.com/serilog/serilog-expressions#implementing-user-defined-functions](https://github.com/serilog/serilog-expressions#implementing-user-defined-functions)


And the code in the Main would be: 

`
    //StaticMemberNameResolver myFunctions = new(typeof(PuedeSerBoot));
    //CompiledExpression expr = SerilogExpression.Compile("EsBoot(ClientAgent)", null, myFunctions);

    Log.Logger = new LoggerConfiguration()
      .ReadFrom.Configuration(config, "Serilog")
      .CreateLogger(); //.CreateBootstrapLogger();
`

Thank you

**Comment by FJGR65** [comment]
Now a doubt arises.

Which of the two alternatives (user-defined function or enricher) is the fastest? That is, which of the two is the one that consumes the least resources?

**Comment by skomis-mm** [comment]
I beleive as long as function compiled to the delegate there is not much differences from enricher code..
The main difference is that in the latter case your log event enriched with the result of `ClientBootAgent` mapping (`Si` or `No`), but in the former it contains raw header value, and only file sink will map it.

**Comment by momt99** [comment]
The exception is also thrown when `theme` is set through the configuration.
My `appsettings.json`:
```json
"WriteTo": [
    {
        "Name": "Console",
        "Args": {
            "formatter": {
                "type": "Serilog.Templates.ExpressionTemplate, Serilog.Expressions",
                "template": "[{@t}]\n{#each k,v in @p}\t{k} = {v}{#delimit}\n{#end}\n",
                "theme": "Serilog.Templates.Themes.TemplateTheme::Literate, Serilog.Expressions"
            }
        }
    }
]
```

**Comment by mrt181** [comment]
@momt99 try this: https://github.com/serilog/serilog-expressions/issues/12#issuecomment-1007907557
