### ISSUE TITLE
Support level formatting `u3` etc. in `ToString()`

### ISSUE THREAD

**Issue by Lanayx** [serilog/serilog-expressions#69]
Example
`{ {myTime: {@t:o} } }` will result in `{"myTime":{}}`

**Comment by nblumhardt** [comment]
Hi Vladimir,

In expressions, format strings can be applied with `ToString()`:

```js
{ {myTime: ToString(@t, "o") } }
```

HTH!

**Comment by Lanayx** [comment]
Thanks, will u3 for level work as well?

**Comment by nblumhardt** [comment]
Currently to do short level formatting in JSON you'll need to plug in a custom function (e.g. `ShortLevelName(@l)`).

Only a couple of lines of code - instructions [here](https://github.com/serilog/serilog-expressions#implementing-user-defined-functions). HTH!

**Comment by Lanayx** [comment]
Right, this is what I have eventually come up with :) You can close the issue if you think that the shortcut formatting should only be available for the text (not JSON) mode.

**Comment by nblumhardt** [comment]
Will give this some more thought - thanks 👍
