### ISSUE TITLE
Only render @p properties if has values

### ISSUE THREAD

**Issue by CxRP** [serilog/serilog-expressions#70]
Hi,

I have the following console output when using an **ExpressionTemplate**

`2022-03-25 12:47:18.271 INFO:  {}`
`2022-03-25 12:47:20.725 INFO: TEST3 {"methodName":"RunCommandLineOptionsAndReturnExitCode","className":"ABC"}`

as you can see from the first line that it is printing the empty `{}` where I have no properties.

What expression do I need to check if the `@p` is _empty/null/zero length_ so as to only render if there are properties?

My expression
`"{@t:yyyy-MM-dd HH:mm:ss.fff} {if @l = 'Verbose' then 'TRACE' else if @l = 'Fatal' then 'Fatal' else if @l = 'Error' then 'ERROR'  else if @l = 'Debug' then 'DEBUG' else if @l = 'Information' then 'INFO' else if @l = 'Warning' then 'WARN' else ''}: {@m} {if @p is not null then {..@p} else ''} {@x}\r\n"`
i.e.  `{if @p is not null then {..@p} else ''}`

Also tried
- `{#if Length({@p}) > 0} {@p} {#else} {#end}`
- `{#if Length(@p) > 0} {@p} {#else} {#end}`

**Comment by nblumhardt** [comment]
Hi! This is currently a bit trickier than it should be - the following should work:

```
{#if Length(Keys(@p)) > 0} {@p} {#else} {#end}

{#if IsDefined(@p[?])} {@p} {#else} {#end}
```

HTH!

**Comment by CxRP** [comment]
Thank you very much @nblumhardt.
The second one worked `{#if IsDefined(@p[?])} {@p} {#else} {#end}`

However, the first one errored with `The function name "Keys" was not recognized.`
