### ISSUE TITLE
[Question] Reading back output file

### ISSUE THREAD

**Issue by LiorBanai** [serilog/serilog-expressions#9]
Hi,
Just a small question regarding the output of using expressions library..
It the output a standard serilog file (json/non json file) that can be consume like other formats? 

The reason why I'm asking is that I have [Serilog Parser](https://github.com/Analogy-LogViewer/Analogy.LogViewer.Serilog), And would like to know if I need to make some modification of reading back files that are created using this package?

**Comment by nblumhardt** [comment]
Hi Lior,

Thanks for the note! The format is 100% configurable, there's no fixed output format (could be JSON in any schema, text, something else...) so probably doesn't make sense to try adding a specific parser for it.

HTH!
Nick

**Comment by LiorBanai** [comment]
Ok,Thanks!
