### ISSUE TITLE
Missing SystemConsoleTheme and some AnsiConsoleTheme

### ISSUE THREAD

**Issue by Freenex1911** [serilog/serilog-expressions#92]
Currently there is `TemplateTheme` available in `ExpressionTemplate` which only includes ANSI templates. I'd like to use the same themes (`SystemConsoleTheme` and `AnsiConsoleTheme`) from the official serilog-sinks-console repository. Currently using my application on some older system (Server 2012 R2) and ANSI is afaik not supported, at least I'm only receiving some weird characters once I use a theme. Using `SystemConsoleTheme.Literate` works fine but it's not available in combination with serilog-expressions.

**Comment by nblumhardt** [comment]
Thanks for dropping us a line; this was a deliberate choice in _Serilog.Expressions_ - dropping `SystemConsoleTheme` saved a little complexity here. Conditionally enabling theming based on the OS version might be your best bet, unfortunately.
